apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    control-plane: capp-controller-manager
  name: capp-controller-manager
  namespace: capi-system
spec:
  replicas: 1
  selector:
    matchLabels:
      control-plane: capp-controller-manager
  template:
    metadata:
      labels:
        control-plane: capp-controller-manager
    spec:
      containers:
      - args:
        - --secure-listen-address=0.0.0.0:8443
        - --upstream=http://127.0.0.1:8080/
        - --logtostderr=true
        - --v=10
        image: gcr.io/kubebuilder/kube-rbac-proxy:v0.4.0
        name: kube-rbac-proxy
        ports:
        - containerPort: 8443
          name: https
      - args:
        - --metrics-addr=127.0.0.1:8080
        - --enable-leader-election
        image: thebsdbox/capp:0.0
        name: manager
        volumeMounts:
        - name: plunderyaml
          mountPath: "/plunderclient.yaml"
          subPath: "plunderclient.yaml"
        securityContext:
          privileged: true
      terminationGracePeriodSeconds: 10
      volumes:
      - name: plunderyaml
        secret:
          secretName: plunder